"""Write docs/three-numbers.js: the regime effect on the yield curve for two matched chains and the formula."""
import json, os
import numpy as np
from verify_three_numbers import QA, THA, SA, QB, KAPPA, matched_chain, invariants, first_order
from three_numbers import stationary, log_bond_stationary, int_Bk

M = 2.0
thB, sB, _ = matched_chain(QB, invariants(QA, THA, SA))
pi = stationary(QA)
Ts = [round(x, 3) for x in np.concatenate([np.linspace(0.25, 5, 20), np.linspace(5.5, 30, 50)])]


def bp(logp, T):
    return -logp / T * 1e4


rows = {'A': [], 'B': [], 'formula': []}
for T in Ts:
    avg = -KAPPA * (pi @ THA) * int_Bk(1, T, KAPPA) + (pi @ SA / 2) * int_Bk(2, T, KAPPA)
    base = bp(avg, T)
    rows['A'].append([T, round(bp(log_bond_stationary(T, M * QA, THA, SA, KAPPA, dps='double'), T) - base, 5)])
    rows['B'].append([T, round(bp(log_bond_stationary(T, M * QB, thB, sB, KAPPA, dps='double'), T) - base, 5)])
    rows['formula'].append([T, round(bp(first_order(T, M * QA, THA, SA), T) - base, 5)])
shapes = {k: [[T, round(KAPPA ** k * int_Bk(k, T, KAPPA) / T, 6)] for T in Ts] for k in [1, 2, 3, 4]}
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'docs', 'three-numbers.js')
with open(out, 'w') as f:
    f.write('// Generated by papers/yield-curve/make_data.py\nvar THREE = ' + json.dumps({'effect': rows, 'shapes': shapes,
            'chainB': {'theta': [round(x, 4) for x in thB], 's': [float('%.3g' % x) for x in sB]}}) + ';\n')
print('wrote', out, 'chain B', thB, sB)
